### ISSUE TITLE
shops having stat purchases

### ISSUE THREAD

**Issue by Roars-Tech** [andreicruceru95/App06-Group#13]
with the shops having stat purchases, is it not possible to gain experience from monsters to increase the adventures level, like with the monster levels? if not given the cost of the upgrade the monsters might need to drop more gold?

**Comment by andreicruceru95** [comment]
I fixed the blacksmith functions. The cost for enchantment is now fixed to
50 gold.

**Comment by andreicruceru95** [comment]
The shop stat purchases were added as an extra way for the player to obtain power.

With we could soon add experience to the player and increase it's level as way to obtain power and replace the shop stats

**Comment by andreicruceru95** [comment]
Gold drop is on the process of being changed : 
1. Instead of going in the player's account it will be spawned next to the player as $ and the player can pick it up. There is a 30% chance of drop. On pickup it will have a random value between 5 and 15 multiplied with the monster's level. Let me know how this sounds

2. On monster kill, there is a 10% chance to drop a lucky chest next to the player. The chest contains 2x, 3x, or 5x the amount of gold it would normally drop.

3. I would like adding more items to the game like before, so there could be a possible items drop. This is however asking for an inventory list and a equipped items list and other extensions like adding value to items, sell items, drop items etc.
This idea will take a bit of time so we can leave it for now
