### ISSUE TITLE
current maps / levels

### ISSUE THREAD

**Issue by Roars-Tech** [andreicruceru95/App06-Group#21]
Town - Starting area, connected to a forest, within the forest is a teleporter to the desert
Dessert - second level, contains a teleporter to the spider cave (can we work around using the teleporter to enter the spider cave? and have the player enter another way? the player will still have to enter the spider cave as part of a quest) then we can use the teleporter to enter the next level. ( I might rename the locations so the story line fits from moving location to location as going from town / forest to desert then to somewhere where a tower would be doesn't seem realistic) 
Tower , ground floor - find the boss, then the stairs leading up
Tower, 1st floor - find the boss, then the stairs leading up
Tower, 2nd floor -  find the boss, then the stairs leading up
Tower, 3rd floor - final boss room? boss guarding the mythical crystal required to return to the centre of town to complete the game 

(let me know if you're adding / taking away floors, can you also show me how you've created the map and I can assist on design for them)

**Comment by andreicruceru95** [comment]
I am happy with that.  Let me know of the name changes.

I added a story class, so it is a lot easier to add/change story.

_ can you also show me how you've created the map_: 
1st step: define a 2D array[rowSize][ColSize](in the world class)
2nd step: create a Map type variable mapName and initialise it by creating a new Map("mapName", 2D array[rowSize][ColSize]) 
3rd step: There is a createMap() method that will create an empty map with borders.  Because of the player's visual field, the map must have a border >= 3. So you call mapName.createMap(typeOfWall, border)
4th step: create a addObjectsToMapName() method where you personalise the map. Eg: add walls ad given locations, add monsters etc.

**Comment by andreicruceru95** [comment]
I can show you an example during our call tomorrow?

**Comment by Roars-Tech** [comment]
yeah, sounds goods 👍

**Comment by andreicruceru95** [comment]
The connections are set up as following:
Fortress (starting point) -> Town (the outskirts of the fortress) -> Forest -> Dessert or Mountain
Mountain -> Dessert
Dessert ->(if player has defeated the fox from Mountain) -> Spider Cave
Spider Cave -> (if player has defeated the Spider Queen) -> Tower 1
Tower1 -> Tower 2 -> Tower 3 -> Tower 4-> Tower 6 (last level) -> Town
